version: "3.8"

services:
  postgres:
    image: postgres:16-alpine
    container_name: nutricoach_postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-nutricoach}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-nutricoach_password}
      POSTGRES_DB: ${POSTGRES_DB:-nutricoach_db}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-nutricoach}"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    name: nutricoach_postgres_data
